config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='item')),
]

products/urls.py
from products.apps import ProductsConfig
from django.urls import path

from products.views import ItemDetailView, page_with_pay_link, success_page, orders_create, basket_pay_link, \
    basket_success_page

app_name = ProductsConfig.name


urlpatterns = [
    path('item/<int:pk>/', ItemDetailView.as_view(), name='detail'),  # Страница просмотра товара
    path('buy/<int:pk>/', page_with_pay_link, name='buy'),  # Страница со ссылкой на оплату
    path('success/<int:pk>/', success_page),  # Страница успешной оплаты товара
    path('basket/', orders_create, name='basket'),  # Страница сбора корзины
    path('basket/<int:pk>/', basket_pay_link, name='buy_basket'),  # Страница со ссылкой на оплату
    path('basket_success/', basket_success_page),  # Страница успешной оплаты корзины
]

products/models.py
from django.db import models

# Create your models here.


NULLABLE = {'blank': True, 'null': True}


class Item(models.Model):

    CUR = (
        ('USD', 'доллары'),
        ('RUB', 'рубли'),
    )  # тут можно добавить валюту

    name = models.CharField(max_length=100, verbose_name='Название', unique=True)
    description = models.TextField(verbose_name='описание', **NULLABLE)
    price = models.IntegerField(verbose_name='цена')
    currency = models.CharField(max_length=10, verbose_name='способ оплаты', choices=CUR)  # валюты две. добавить можно в CUR

    def __str__(self):
        return f'{self.name} - {self.price}{self.currency}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Order(models.Model):  # С помощью корзины можно покупать сразу несколько товаров
    items = models.ManyToManyField(Item, verbose_name='Товары')

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return ', '.join(str(item) for item in self.items.all())

products/forms.py
from django import forms

from products.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('items', )

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView

from products.forms import OrderForm
from products.models import Item, Order
from products.services import get_payment, get_basket_payment


# Create your views here.


class ItemDetailView(DetailView):
    model = Item


def page_with_pay_link(request, pk):

    item = get_object_or_404(Item, pk=pk)

    session = get_payment(item)
    context = {"payment_link": session.url}  # Ссылка на стр оплаты

    return render(request, 'products/page_with_link.html', context)


def success_page(request, pk):

    item = get_object_or_404(Item, pk=pk)
    context = {"item": item.name}

    return render(request, 'products/success_page.html', context)


def orders_create(request):

    if request.method == 'POST':
        form = OrderForm(request.POST)  # форма для создания корзины
        order = form.save()
        return redirect(f'/basket/{order.id}')  # при успешном создании отправляет на стр со ссылкой на оплату
    else:
        form = OrderForm()

    return render(request, 'products/basket.html', {'form': form})


def basket_pay_link(request, pk):

    order = get_object_or_404(Order, pk=pk)

    session = get_basket_payment(order)
    context = {"payment_link": session.url}  # Ссылка на стр оплаты

    return render(request, 'products/page_with_link.html', context)


def basket_success_page(request):

    context = {"item": 'собранной корзины'}  # тут важно передать контекст: success_page.html используется и для item
    return render(request, 'products/success_page.html', context)

products/templates/products/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Top navbar example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">Меню</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Ко всем товарам</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'item:basket' %}">Корзина</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
      </div>
    </nav>

    {% block content %}
    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

products/templates/products/basket.html
{% extends 'products/base.html' %}

{% block content %}
    <main role="main" class="container">
      <div class="jumbotron text-center mx-auto">
        <h1>Корзина</h1>
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-lg btn-primary">Купить  &raquo;</button>
          </form>

      </div>
    </main>
{% endblock %}

products/templates/products/item_detail.html
{% extends 'products/base.html' %}

{% block content %}
    <main role="main" class="container">
      <div class="jumbotron text-center mx-auto">
        <h1>{{ object.name }}</h1>
        <p class="lead">{{ object.description }}</p>
        <a class="btn btn-lg btn-primary" href="{% url 'item:buy' object.id %}" role="button">Купить за {{ object.price }} {{ object.currency }} &raquo;</a>
      </div>
    </main>
{% endblock %}

products/templates/products/page_with_link.html
{% extends 'products/base.html' %}

{% block content %}
    <main role="main" class="container">
      <div class="jumbotron text-center mx-auto">
        <h1>Ваша ссылка на оплату:</h1>
        <a class="btn btn-lg btn-primary" href="{{ payment_link }}" role="button">Оплатить &raquo;</a>
      </div>
    </main>
{% endblock %}

products/templates/products/success_page.html
{% extends 'products/base.html' %}

{% block content %}
    <main role="main" class="container">
      <div class="jumbotron text-center mx-auto">
        <h1>Спасибо за покупку {{ item }}</h1>
      </div>
    </main>
{% endblock %}